### ISSUE TITLE
It's giving CORS Error all of a sudden!! 

### ISSUE THREAD

**Issue by mohithgupta** [sumitkolhe/krates#2]
It was fine till yesterday, I don't get it why it suddenly started giving CORS error! 

![Screenshot (328)](https://user-images.githubusercontent.com/50448748/148640551-547d5ce4-8b35-429d-ad60-eef44dab9b4b.png)

Adding The URL as a proxy in the package.json doesn't seem to work. My project is in progress, so please solve it ASAP!

**Comment by mohithgupta** [comment]
I think the website is Down or Something!!🤧🤧🤧

**Comment by sumitkolhe** [comment]
this [commit](https://github.com/sumitkolhe/krates/commit/0b8ab0eea337a1623304ad8de320da4b3569771a)should fix the issue.

**Comment by sumitkolhe** [comment]
issue is resolved. closing this.
